apiVersion: v1
kind: Service
metadata:
  name: {{ include "volmetd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "volmetd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.headless }}
  clusterIP: None
  {{- end }}
  selector:
    {{- include "volmetd.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
