apiVersion: v1
kind: Service
metadata:
  name: volmetd
  namespace: volmetd
  labels:
    app.kubernetes.io/name: volmetd
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: volmetd
  ports:
    - name: metrics
      port: 6060
      targetPort: metrics
      protocol: TCP
