apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: volmetd
  namespace: volmetd
  labels:
    app.kubernetes.io/name: volmetd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: volmetd
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
